# Default values for kubestellar-controller-manager chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# name of control plane to set as WDS
ControlPlaneName: wds1

# list of allowed Kubernetes api groups, comma separated.
# If not specified, all api groups are allowed. 
# When set by --set with helm CLI, use the format
# "<group1>\,<group2>\,<groupN>" with "" and escaped \,
APIGroups:

# The name of the Inventory and Transport Space to use.
# Empty string means that there must be only one and that
# is the one to use.
ITSName: ""

ControllerManager:
  # The -v setting for the controller-manager
  Verbosity: 2
