apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: ocm
  labels:
    kflex.kubestellar.io/cptype: its
spec:
  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{.HookName}}"
    spec:
      template:
        spec:
          containers:
          - name: "{{.HookName}}-ocm"
            image: quay.io/kubestellar/clusteradm:0.8.2
            args:
            - init
            env:
            - name: KUBECONFIG
              value: "/etc/kube/config-incluster"
            volumeMounts:
            - name: kubeconfig
              mountPath: "/etc/kube"
              readOnly: true
          - name: "{{.HookName}}-statusaddon"
            image: quay.io/kubestellar/helm:3.14.0
            args:
              - upgrade
              - --install
              - status-addon
              - oci://ghcr.io/kubestellar/ocm-status-addon-chart
              - --version
              - v0.2.0-rc11
              - --namespace
              - open-cluster-management
              - --create-namespace
            env:
            - name: HELM_CONFIG_HOME
              value: "/tmp"
            - name: HELM_CACHE_HOME
              value: "/tmp"
            - name: KUBECONFIG
              value: "/etc/kube/config-incluster"
            volumeMounts:
            - name: kubeconfig
              mountPath: "/etc/kube"
              readOnly: true
          volumes:
          - name: kubeconfig
            secret:
              secretName: vc-vcluster
          restartPolicy: Never
      backoffLimit: 1
